version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contactsdb
    volumes:
      - contact_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - contact_net

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - PGHOST=db
      - PGUSER=user
      - PGPASSWORD=password
      - PGDATABASE=contactsdb
      - PGPORT=5432
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - contact_net

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - contact_net

volumes:
  contact_db_data:

networks:
  contact_net:

